### ISSUE TITLE
Mirth doesn't start using JVM 1.6

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#224]
Mirth doesn't start using JVM 1.6

No messages. No clues.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-205
Reporter: albertosaez
Created: 2006-12-19T09:53:10.000-0800

**Comment by rbeckman-nextgen** [comment]
I'm running into this issue as well.  Unfortunately I'm running Vista and the only offically supported JRE for Vista is 1.6, so I may be blocked at the moment.  I'll give 1.5 a shot and update this issue.

An ETA for a fix would definetely help me figure out I should build an XP machine for testing purposes.

Thanks.

Imported Comment. Original Details:
Author: justinwi
Created: 2007-01-17T00:50:31.000-0800

**Comment by rbeckman-nextgen** [comment]
Justin,

We haven't planned 1.6 support in the 1.3.x release line, however it is tentatively scheduled for 1.4. 1.4 is 3 to 6 months off.
(Note that 1.6 support means taking full advantage of the features 1.6 bring (i.e. embedded db, etc). If a small fix is available to allow Mirth to startup in J1.6, we will roll it into the next 1.3.x release).

-Chris

Imported Comment. Original Details:
Author: chrisl
Created: 2007-01-17T01:05:20.000-0800

**Comment by rbeckman-nextgen** [comment]
Good news, I was able to get Mirth started on 1.5.10; no issues so far.  I also found out Sun is going to release 1.5.11 sometime this month which will officially support Vista, so no major rush on supporting 1.6 from this standpoint.

Thanks,
Justin

Imported Comment. Original Details:
Author: justinwi
Created: 2007-01-19T00:30:51.000-0800

**Comment by rbeckman-nextgen** [comment]
Vista:

I first ran Mirth on Vista with Java 1.5 installed.  It had the version problem as expected, but changing the jnlp to accept versions 1.5+ fixed it.  I went ahead and committed that fix.  Another potential problem could be that the latest 1.5 release 11 is the only version of 1.5 currently supported on vista, but it is not yet available for automatic install/update through webstart.  It may auto update to 1.6, however, so I'll move onto those results.  Worst case scenario, people will have to manually install the 1.5 JRE on Vista. 

JRE 1.6:

I installed the 1.6 JDK and JRE on my computer here at work.  With the runtime set as java 1.6 the server started up fine.  Webstart did not work at first (for some reason it was trying to download the 1.5 SDK), but rebuilding with that fix I committed earlier fixed this problem as well!  There seem to be no problems running both the mirth server and client on Java 1.6.

JDK 1.6:

Compiling mirth is a different story.  There are a few problems with 1.6.  Both java.sql.Connection and java.sql.DataSource have changed dramatically (a ton of new options though).  We have compilation errors because we do not implement 15 new abstract methods from Connection and 2 new abstract methods from DataSource.  I implemented them (auto-implement) and after some quick changes the server compiled and ran fine.  In this case, however, it no longer compiles on 1.5 because the new methods use objects that didn't exist in 1.5.  We can decide if we want to switch over to building on 1.6 in the future and take advantage of a lot of new features, but I am not sure how mirth built on 1.6 will run on a 1.5 JRE.

All in all, we should be fine for this release.  All that was needed to run on java 1.6 and vista was a small fix the jnlp.  I didn't encounter any other issues that people stated they did with Java 1.6.


Imported Comment. Original Details:
Author: jacobb
Created: 2007-03-15T12:03:31.000-0700
