### ISSUE TITLE
Client throws exception when a DICOM file is attempted to be loaded into a filter/transformer template

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2180]
In 2.1.1, DICOMSerializer did not reference DICOMUtil, but in 2.2.1 it does. However, DICOMUtil is located in server/util, which is not included in the client-core library. So a NoClassDefFoundError is thrown when one tries to load a DICOM file into an inbound/outbound template in the Administrator.

Either server/util needs to be included in the create-client-core target, or DICOMUtil needs to be moved from server/util to an already included package like connect/util. I'll attach a patch for the server build file to add server/util to client-core.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2237
Reporter: narupley
Created: 2012-10-05T11:01:00.000-0700

**Comment by rbeckman-nextgen** [comment]
DICOMUtil references MessageController which isn't in client-core. Also it references IOUtils from Commons IO, but the server now uses 2.3 while the client still is on 2.1, so that will have to be updated. We might want to split this up into two classes, one in connect/util for all the shared stuff and the server-specific stuff can be left in the server/util class.

Imported Comment. Original Details:
Author: narupley
Created: 2012-12-12T10:36:35.000-0800

**Comment by rbeckman-nextgen** [comment]
The client should have still worked with Commons IO 2.1, since 2.x is backwards compatible, but I updated the libraries anyway as a part of MIRTH-2250 to keep them consistent across projects.

Imported Comment. Original Details:
Author: jacobb
Created: 2012-12-12T18:49:21.000-0800

**Comment by rbeckman-nextgen** [comment]
This has been resolved in both 2.2.2 and 3.0.0 Beta 1.

Imported Comment. Original Details:
Author: jacobb
Created: 2012-12-13T18:02:24.000-0800

**Comment by rbeckman-nextgen** [comment]
Hi, I'm new with Mirth Connect.. Can some body explain to me how to install this patch ? thanks

Imported Comment. Original Details:
Author: dasmah@hotmail.com
Created: 2013-05-03T00:11:29.000-0700

**Comment by rbeckman-nextgen** [comment]
The patch I originally attached is just a quick-fix and isn't recommended; we took a different route altogether for the 2.2.2 and 3.0 resolutions. 

2.2.2 will be released soon, but if you need it fixed now I recommend checking out the source code (tags/2.2.1), looking at the branches/2.x changeset related to this issue (viewable under "Source"), and making the modifications as necessary. Then you'll need to build the project, verify that everything works as expected, and replace mirth-client-core.jar and mirth-server.jar. It's easy to mess something up doing this, so this is an "at your own risk" thing. If you're not familiar with Java, Ant, or IDEs I would recommend finding someone who is.

Imported Comment. Original Details:
Author: narupley
Created: 2013-05-03T07:20:57.000-0700
