### ISSUE TITLE
mccommand not working in 2.2.0.5746.b1112

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1984]
Grabbed this build off the build box and did:

cd /opt
tar zxvf ~/stevek/mirthconnect-2.2.0.5746.b1112-unix.tar.gz 
mv Mirth\ Connect mirthconnect-2.2.0.5746.b1112
cd mirthconnect-2.2.0.5746.b1112
./mcserver start

-- in another window --
cd /opt/mirthconnect-2.2.0.5746.b1112
./mccommand 
java.lang.NoClassDefFoundError: org/apache/commons/io/filefilter/IOFileFilter
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2427)
	at java.lang.Class.getDeclaredMethod(Class.java:1935)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.filefilter.IOFileFilter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	... 5 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2018
Reporter: steven_kehlet
Created: 2011-11-18T15:57:27.000-0800

**Comment by rbeckman-nextgen** [comment]
Updated build reference to Commons IO and Lang.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-11-18T16:41:29.000-0800

**Comment by rbeckman-nextgen** [comment]
Tested with mirthconnect-2.2.0.5781.b1145. Same process as above. Now I get:

[10:44 AM] appliance:/opt/mirthconnect-2.2.0.5781.b1145 # ./mccommand 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mirth.connect.cli.launcher.CommandLineLauncher.main(CommandLineLauncher.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/contrib/ssl/EasySSLProtocolSocketFactory
	at com.mirth.connect.client.core.ServerConnection.<init>(ServerConnection.java:55)
	at com.mirth.connect.client.core.ServerConnection.<init>(ServerConnection.java:40)
	at com.mirth.connect.client.core.ServerConnectionFactory.createServerConnection(ServerConnectionFactory.java:14)
	at com.mirth.connect.client.core.Client.<init>(Client.java:85)
	at com.mirth.connect.cli.CommandLineInterface.runShell(CommandLineInterface.java:145)
	at com.mirth.connect.cli.CommandLineInterface.run(CommandLineInterface.java:131)
	at com.mirth.connect.cli.CommandLineInterface.<init>(CommandLineInterface.java:74)
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.httpclient.contrib.ssl.EasySSLProtocolSocketFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	... 18 more

Imported Comment. Original Details:
Author: steven_kehlet
Created: 2011-12-02T10:45:58.000-0800

**Comment by rbeckman-nextgen** [comment]
SSL classes were replaced with Not-Yet-Commons-SSL as parth of MIRTH-1796. Added the jar file to the CLI classpath.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-12-02T11:23:17.000-0800
